workshops/test/test_util.py: Decode result byte stream
Avoid:

  ======================================================================
  ERROR: test_event_name_dropped (workshops.test.test_util.BulkUploadUsersViewTestCase)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/.../amy/workshops/test/test_util.py", line 207, in test_event_name_dropped
      self.assertNotIn("foobar", rv.content)
    File "/usr/lib64/python3.4/unittest/case.py", line 1060, in assertNotIn
      if member in container:
  TypeError: Type str doesn't support the buffer API

  ----------------------------------------------------------------------
  Ran 43 tests in 2.640s

by decoding to Unicode.  I use cgi.parse_header [1] to get the charset
(e.g. "utf-8") from the Content-Type header (e.g. "text/html;
charset=utf-8").

This is the same fix I landed in 0622076f (workshops/test/base.py:
Decode result byte stream, 2015-01-20), but the test_util module
landed later in d89c76a4 (Move csv parsing to util and add test,
2015-01-25).

[1]: https://docs.python.org/3/library/cgi.html#cgi.parse_header