workshops/models.py: Add custom PersonManager to Person model
As suggested in the docs, where the paragraph before [1] has:

  You should also define a custom manager for your User model. If your
  User model defines username, email, is_staff, is_active,
  is_superuser, last_login, and date_joined fields the same as
  Django’s default User, you can just install Django’s UserManager;
  however, if your User model defines different fields, you will need
  to define a custom manager that extends BaseUserManager providing
  two additional methods:

We don't define is_staff or is_active, so we're using a custom manager
extending BaseUserManager.  Our implementation is based on the example
[2], including the use of normalize_email [3].  We don't need local
value checks in our create_* methods, because Django figures that out
from our field definitions:

  $ python3.4 manage.py createsuperuser
  Username:
  Error: This field cannot be blank.
  Username: wking
  Error: That username is already taken.
  Username: wking-2
  Personal:
  Error: This field cannot be blank.
  Personal: W. Trevor
  Family:
  Error: This field cannot be blank.
  Family: King
  Email:
  Password:
  Password (again):
  Error: Blank passwords aren't allowed.
  Password: ***
  Password (again): ***
  Superuser created successfully.

[1]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.CustomUserManager
[2]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#a-full-example
[3]: https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.BaseUserManager.normalize_email