workshops/models.py: Drop PersonQuerySet and PersonManager
These don't actually save us any work, since the instructors() view is
simpler without them.

They also break superuser addition when using Person as the user
model.  In my use-person-for-auth branch (swcarpentry/amy#147) without
this change, I see:

  $ python3.4 ./manage.py syncdb
  ...
  You have installed Django's auth system, and don't have any superusers defined.
  Would you like to create one now? (yes/no): yes
  Username: ...
  Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
      execute_from_command_line(sys.argv)
    File "/.../django/core/management/__init__.py", line 385, in execute_from_command_line
      utility.execute()
    File "/.../django/core/management/__init__.py", line 377, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/.../django/core/management/base.py", line 288, in run_from_argv
      self.execute(*args, **options.__dict__)
    File "/.../django/core/management/base.py", line 338, in execute
      output = self.handle(*args, **options)
    File "/.../django/core/management/base.py", line 533, in handle
      return self.handle_noargs(**options)
    File "/.../django/core/management/commands/syncdb.py", line 46, in handle_noargs
      call_command("createsuperuser", interactive=True, database=options['database'])
    File "/.../django/core/management/__init__.py", line 115, in call_command
      return klass.execute(*args, **defaults)
    File "/.../django/contrib/auth/management/commands/createsuperuser.py", line 55, in execute
      return super(Command, self).execute(*args, **options)
    File "/.../django/core/management/base.py", line 338, in execute
      output = self.handle(*args, **options)
    File "/.../django/contrib/auth/management/commands/createsuperuser.py", line 113, in handle
      self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  AttributeError: 'PersonManager' object has no attribute 'get_by_natural_key'