workshops/util.py: Python 3 compatibility for StringIO import
In Python 3 the module has moved [1] from cStringIO [2] to io [3].

Avoid:

  ======================================================================
  ERROR: workshops.test.test_util (unittest.loader.ModuleImportFailure)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib64/python3.4/unittest/case.py", line 58, in testPartExecutor
      yield
    File "/usr/lib64/python3.4/unittest/case.py", line 577, in run
      testMethod()
    File "/usr/lib64/python3.4/unittest/loader.py", line 32, in testFailure
      raise exception
  ImportError: Failed to import test module: workshops.test.test_util
  Traceback (most recent call last):
    File "/usr/lib64/python3.4/unittest/loader.py", line 312, in _find_tests
      module = self._get_module_from_name(name)
    File "/usr/lib64/python3.4/unittest/loader.py", line 290, in _get_module_from_name
      __import__(name)
    File "/.../amy/workshops/test/test_util.py", line 16, in <module>
      from ..util import upload_person_task_csv, verify_upload_person_task
    File "/.../amy/workshops/util.py", line 3, in <module>
      import cStringIO
  ImportError: No module named 'cStringIO'

which we've had since the old cStringIO import crept in with b29ff611
(Replace static bulk add template with generated CSV, 2015-01-26).

[1]: https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit
[2]: https://docs.python.org/2/library/stringio.html#cStringIO.StringIO
[3]: https://docs.python.org/3/library/io.html#io.StringIO