workshops/test/base.py: Assign a group and permission to Ironman, Ron, and Spiderman
Avoid:

  ======================================================================
  FAIL: test_edit_person_email_when_airport_not_set (workshops.test.test_person.TestPerson)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/.../amy/workshops/test/test_person.py", line 23, in test_edit_person_email_when_airport_not_set
      self._test_edit_person_email(self.spiderman)
    File "/.../amy/workshops/test/test_person.py", line 40, in _test_edit_person_email
      url, values = self._get_initial_form('person_edit', person.id)
    File "/.../amy/workshops/test/base.py", line 211, in _get_initial_form
      values = self._get_form_data(doc)
    File "/.../amy/workshops/test/base.py", line 225, in _get_form_data
      for s in form.findall('.//select')])
    File "/.../amy/workshops/test/base.py", line 225, in <listcomp>
      for s in form.findall('.//select')])
    File "/.../amy/workshops/test/base.py", line 203, in _get_selected
      'Either zero or multiple selections for node {0}'.format(node.attrib['id'])
  AssertionError: Either zero or multiple selections for node id_groups

And similar errors in test_edit_person_email_when_all_fields_set and
test_edit_person_empty_family_name when the id_groups and
id_user_permissions selection widgets didn't have anything selected.
Giving permission for badge admin to instructors and non-instructors
doesn't make much sense, but I didn't see an easy way to turn off the
_get_selected check for fields where we expect there to be no selected
options.