workshops/test/base.py: Decode result byte stream
Avoid:

  $ python3.4 ./manage.py test
  ...
  ======================================================================
  ERROR: test_match_instructors_on_one_skill (workshops.test.test_instructors.TestLocateInstructors)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/.../amy/workshops/test/test_instructors.py", line 64, in test_match_instructors_on_one_skill
      doc = self._check_status_code_and_parse(response, 200)
    File "/.../amy/workshops/test/base.py", line 157, in _check_status_code_and_parse
      doc = self._parse(response.content)
    File "/.../amy/workshops/test/base.py", line 130, in _parse
      if settings.TEMPLATE_STRING_IF_INVALID in content:
  TypeError: Type str doesn't support the buffer API

by decoding to Unicode.  I use cgi.parse_header [1] to get the charset
(e.g. "utf-8") from the Content-Type header (e.g. "text/html;
charset=utf-8").

[1]: https://docs.python.org/3/library/cgi.html#cgi.parse_header