workshops/test/test_event.py: Test adding two minimal Events
This currently fails:

  $ python3.4 manage.py test workshops.test.test_event.TestEventViews.test_add_two_minimal_events
  ...
  ======================================================================
  FAIL: test_add_two_minimal_events (workshops.test.test_event.TestEventViews)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/.../amy/workshops/test/test_event.py", line 237, in test_add_two_minimal_events
      self._check_status_code_and_parse(response, 200)
    File "/.../amy/workshops/test/base.py", line 214, in _check_status_code_and_parse
      assert False, 'error messages in {0}:\n{1}'.format(caller, errors)
  AssertionError: error messages in test_add_two_minimal_events:
  Event with this Url already exists.

  ----------------------------------------------------------------------
  ...

But we can fix it by getting NULL as the default for Event.url, since
NULL values don't violate uniqueness [1] but empty strings will [2].

[1]: https://code.djangoproject.com/ticket/9039
[2]: https://code.djangoproject.com/ticket/4136